[package]
name = "password-funcs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
config.workspace = true
luahelper.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "3", features = ["apple-native"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3", features = ["windows-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3", features = ["sync-secret-service"] }

[target.'cfg(target_os = "freebsd")'.dependencies]
keyring = { version = "3", features = ["sync-secret-service"] }
